---
# Ansible playbook for a Munin monitoring server.
#
# @author Jeff Geerling (2014).

- hosts: munin
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.apache
    - geerlingguy.munin
    - geerlingguy.munin-node
